In [2]:
from sudoku_rust import solve
import numpy as np
import time

In [3]:
# filepath = 'data/evil_3.csv'
filepath = 'data/badbad.csv'
x = np.loadtxt(filepath, delimiter=',').astype(np.uint16)
x

array([[1, 3, 0, 7, 9, 0, 0, 4, 5],
       [0, 0, 5, 0, 0, 0, 0, 0, 6],
       [2, 0, 0, 0, 8, 0, 9, 0, 0],
       [3, 1, 0, 4, 6, 5, 8, 0, 0],
       [4, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 0, 7, 9, 3, 2, 0, 1, 4],
       [0, 0, 3, 0, 7, 0, 0, 0, 8],
       [7, 0, 0, 0, 0, 0, 3, 0, 0],
       [8, 9, 0, 0, 5, 4, 0, 2, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint16)

In [4]:
start = time.perf_counter()
y = solve(x)
end = time.perf_counter()
elapsed = end - start
print(y)
print(f'elapsed time: {elapsed:.6f}')

[[1 3 0 7 9 0 0 4 5]
 [0 0 5 0 0 0 0 0 6]
 [2 0 0 0 8 0 9 0 0]
 [3 1 0 4 6 5 8 0 0]
 [4 0 0 0 0 0 0 0 2]
 [0 0 7 9 3 2 0 1 4]
 [0 0 3 0 7 0 0 0 8]
 [7 0 0 0 0 0 3 0 0]
 [8 9 0 0 5 4 0 2 9]]
elapsed time: 0.000217


In [4]:
from timeit import timeit

my_list = list(range(1_000_000))
my_set = set(range(1_000_000))

list_time = timeit('999_999 in my_list', number=1000, globals=globals())
print(f'List: {list_time:.6f} seconds')

set_time = timeit('999_999 in my_set', number=1000, globals=globals())
print(f'Set: {set_time:.6f} seconds')

speed_difference = (list_time - set_time) / list_time * 100
print(f'{speed_difference:.3f}% faster')

List: 9.506636 seconds
Set: 0.000039 seconds
100.000% faster


In [5]:
999_999 in my_list

True